### ISSUE TITLE
Feature Request: Include Locked Tiles in Tile Scroll

### ISSUE THREAD

**Issue by MagicOriole** [theripper93/tile-sort#1]
It appears any locked tiles do not show up in Tile Scroll. Is it possible to include this in the module? If not, feel free to close this. Apologies if this is not the correct way to use GitHub Issues.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
